# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fe24klassen
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bonzAI

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam: 
    role: ${env:ROLE}

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  postBooking:
    handler: functions/postBooking/index.handler
    events:
      - httpApi:
          path: /book
          method: post

  getBookings:
    handler: functions/getBookings/index.handler
    events:
      - httpApi:
          path: /bookings
          method: get

  updateBooking:
    handler: functions/updateBooking/index.handler
    events:
      - httpApi:
          path: /update/{id}
          method: put

resources:
  Resources:
    BonzAIDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BonzAIDataTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S # S står String som i datatyp
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH # HASH = Partition key
          - AttributeName: sk
            KeyType: RANGE # RANGE = Sort key
        BillingMode: PAY_PER_REQUEST